# Generated by Django 6.1.1 on 2026-09-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='jabatan',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
